workflows:
  android-ios-workflow:
    name: Android and iOS Workflow
    jobs:
      - android-build:
          name: Android Build
          max_build_duration: 120
          environment:
            android_signing:
              - keystore_reference
            groups:
              - google_play
            vars:
              PACKAGE_NAME: "io.codemagic.fluttersample"
              GOOGLE_PLAY_TRACK: alpha
            flutter: stable
          scripts:
            - name: Set up local.properties
              script: | 
                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
            - name: Get Flutter packages
              script: | 
                flutter packages pub get
            - name: Flutter analyze
              script: | 
                flutter analyze
            - name: Flutter unit tests
              script: | 
                flutter test
              ignore_failure: true
            - name: Build APK with Flutter
              script: | 
                flutter build apk --release \
                  --build-name=1.0.$BUILD_NUMBER \
                  --build-number=$BUILD_NUMBER
          artifacts:
            - build/**/outputs/**/*.apk
            - build/**/outputs/**/mapping.txt
            - flutter_drive.log
            - build/app/outputs/android_builds/*.apk   # Customize this path for Android APK builds
          publishing:  # No publishing for Android
            email:
              recipients:
                - user_1@example.com
                - user_2@example.com
              notify:
                success: true
                failure: false

      - ios-build:
          name: iOS Build
          max_build_duration: 120
          integrations:
            app_store_connect: codemagic
          environment:
            ios_signing:
              distribution_type: app_store
              bundle_identifier: io.codemagic.fluttersample
            vars:
              APP_STORE_APPLE_ID: 1555555551
            flutter: stable
          scripts:
            - name: Set up code signing settings on Xcode project
              script: | 
                xcode-project use-profiles
            - name: Get Flutter packages
              script: | 
                flutter packages pub get
            - name: Install pods
              script: | 
                find . -name "Podfile" -execdir pod install \;
            - name: Flutter analyze
              script: | 
                flutter analyze
            - name: Flutter unit tests
              script: | 
                flutter test
              ignore_failure: true
            - name: Flutter build ipa
              script: | 
                flutter build ipa --release \
                  --build-name=1.0.0 \
                  --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)) \
                  --export-options-plist=/Users/builder/export_options.plist
          artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - flutter_drive.log
            - build/app/outputs/ios_builds/*.ipa  # Customize this path for iOS builds
          publishing:  # No publishing for iOS
            email:
              recipients:
                - user_1@example.com
                - user_2@example.com
              notify:
                success: true
                failure: false
