// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYjKPKjXT-h9LZ8EJhsQMw5bOMvOaKW9M',
    appId: '1:435003970752:web:0ea287bc674add0f5e0925',
    messagingSenderId: '435003970752',
    projectId: 'webviewapp-1e7d9',
    authDomain: 'webviewapp-1e7d9.firebaseapp.com',
    storageBucket: 'webviewapp-1e7d9.appspot.com',
    measurementId: 'G-VLSE2EKJHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_L42ahcaew0nLxai289K42mHJV3Ki_M',
    appId: '1:435003970752:android:687997a9f7d0a1e95e0925',
    messagingSenderId: '435003970752',
    projectId: 'webviewapp-1e7d9',
    storageBucket: 'webviewapp-1e7d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ2Xab3ve16uLMqelF3cUwAq9neB12PSU',
    appId: '1:435003970752:ios:265b0d87c75e45175e0925',
    messagingSenderId: '435003970752',
    projectId: 'webviewapp-1e7d9',
    storageBucket: 'webviewapp-1e7d9.appspot.com',
    iosBundleId: 'com.indicussoftware.webviewapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ2Xab3ve16uLMqelF3cUwAq9neB12PSU',
    appId: '1:435003970752:ios:5ff364125aabb7f05e0925',
    messagingSenderId: '435003970752',
    projectId: 'webviewapp-1e7d9',
    storageBucket: 'webviewapp-1e7d9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
