// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWtrnNnOWx_U6EUFY44ZQon_pcrLJ4OuQ',
    appId: '1:873751623961:web:2b968dd57dff31a78f2d88',
    messagingSenderId: '873751623961',
    projectId: 'webview-d0eac',
    authDomain: 'webview-d0eac.firebaseapp.com',
    storageBucket: 'webview-d0eac.appspot.com',
    measurementId: 'G-FJED94Q0N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGp20KDGUY-MwT9Fh--bc_Z3lNCUMO0Y',
    appId: '1:873751623961:android:d1838a3ba223a1898f2d88',
    messagingSenderId: '873751623961',
    projectId: 'webview-d0eac',
    storageBucket: 'webview-d0eac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdscRUBDm1wchcsWslO2NJCUC-d38qwAY',
    appId: '1:873751623961:ios:b728ca23944dae8f8f2d88',
    messagingSenderId: '873751623961',
    projectId: 'webview-d0eac',
    storageBucket: 'webview-d0eac.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdscRUBDm1wchcsWslO2NJCUC-d38qwAY',
    appId: '1:873751623961:ios:9df052dd8c3da7268f2d88',
    messagingSenderId: '873751623961',
    projectId: 'webview-d0eac',
    storageBucket: 'webview-d0eac.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
